#pragma once

enum EHUDItem
{
	HUD_ITEM_TRESPASSING_ICON = 0,
	HUD_ITEM_BEING_WATCHED_ICON = 1,
	HUD_ITEM_AI_STATE_ICON = 2,
	HUD_ITEM_CLOSE_COMBAT = 3,
	HUD_ITEM_CLOSE_COMBAT_RESULT = 4,
	HUD_ITEM_WEAPON_SELECTION = 5,
	HUD_ITEM_WEAPON_DISPLAY = 6,
	HUD_ITEM_THREAT_RADAR = 7,
	HUD_ITEM_SHOW_THREATS = 8,
	HUD_ITEM_FOCUS_BAR = 9,
	HUD_ITEM_BOSS_HEALTHBAR = 10,
	HUD_ITEM_DARE_TIMER = 11,
	HUD_ITEM_PROFILE_DATA = 12,
	HUD_ITEM_DEBUGLOG = 13,
	HUD_ITEM_SCORE_INFO_MESSAGE = 14,
	HUD_ITEM_RATING_TRACKER = 15,
	HUD_ITEM_UNKNOWN_1 = 16,
	HUD_ITEM_TARGET_TRACKER = 17,
	HUD_ITEM_UNKNOWN_2 = 18,
	HUD_ITEM_UNKNOWN_3 = 19,
	HUD_ITEM_HEALTH_BAR = 20,
	HUD_ITEM_OBJECTIVE_MESSAGE = 21,
	HUD_ITEM_ITEM_HOTBAR = 22,
	HUD_ITEM_NUM = 23,
	
};
